### ISSUE TITLE
[Accordion] re-add moz-focus-inner class

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2419]
In https://github.com/devtools-html/debugger.html/pull/2386 we accidentally removed a style that's not autoprefixed for button focus states

```css
accordion .header-buttons button::-moz-focus-inner {		
  border: none;
}
```
