### ISSUE TITLE
[Editor] Polish the conditional breakpoint panel

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2918]
I think there are a couple of small polish items we can make in the panel that would help a lot:

- [x] update the placeholder text color to be the softer comment color ` var(--theme-comment-alt);` I think
- [x] center the guillemet `>>` in the gutter
- [x] left align the placeholder text with the gutter so it is slightly to the right of the gutter

Feel free to take any of these and make individual PRs. As a reference, the panel is [here] and we toggle the panel [here][t]

![](https://cloud.githubusercontent.com/assets/1755089/26117512/72a26d58-3a84-11e7-8899-3f96047361b7.gif)

Here's some basic CSS for updating the prompt:

```css
.conditional-breakpoint-panel .prompt {
    font-size: 1.8em;
    color: var(--theme-comment-alt);
    padding-left: 3px;
    width: 30px;
    text-align: right;
    padding-right: 3px;
}
```

After the fix, the UI looks like.

<img src='https://shipusercontent.com/ca35e1133c8928996767ab41360f3e6d/Screen%20Shot%202017-05-16%20at%205.34.04%20PM.png' title='Screen Shot 2017-05-16 at 5.34.04 PM.png' width=1106>

The one gotcha will supporting dynamic gutter widths which are set in this function
`resizeBreakpointGutter`. 

[here]:https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/ConditionalPanel.js#L1
[t]:https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/index.js#L487-L521
