### ISSUE TITLE
Make launchpad styles consistent w/ the panel

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4390]
We have two issues that i know about, there might be more:

- [x] the editor should be monospaced. THis is caused by `--monospace-font-family` not being set because `:root.html [platform="mac"]` doesn't match.
- [x] chrome font sizes are 13px because `font: message-box` does not set, which defaults to font-size 11. If you're curious, message-box is part of the [spec][s] :)

[s]:https://developer.mozilla.org/en-US/docs/Web/CSS/font

**Comment by jasonLaster** [comment]
that would be nice!

**Comment by jasonLaster** [comment]
Okay... I investigated a bit and found that common.css is loaded but found that the css doesnt hit

```css

:root.html [platform="mac"] {
  --monospace-font-family: Menlo, monospace;
}

:root.html [platform="win"] {
  --monospace-font-family: Consolas, monospace;
}
```

<img src='https://shipusercontent.com/bca216cbde7b4d7bf9bb4816c8922433/Screen%20Shot%202017-10-17%20at%207.25.06%20PM.png' title='Screen Shot 2017-10-17 at 7.25.06 PM.png' width=703>
