### ISSUE TITLE
[telemetry] open_file

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6695]
```yaml
Events.yaml:
devtools.main:
  open_file:
    objects: ["debugger"],
    bug_numbers: [1463108]
    notification_emails: ["dev-developer-tools@lists.mozilla.org", "hkirschner@mozilla.com"]
    record_in_processes: ["main"]
    description: User has selected a file in the debugger.
    release_channel_collection: opt-out
    expiry_version: never
    extra_keys:
      mimetype: The mimetype of the file.
      sourcemapped: Is the file sourcemapped?
      wasm: Is the file wasm?
      gernerated: Is the file generated?
      time_to_load: How long did the file take to load in ms?
      loaded: Was the file already loaded?
      framework: react, angular, ember, vue, backbone, other.
      minified: Is the file minified?
      size: How large is the file in bytes.
      path: Web path to the file e.g. "caught-exception/exception/pausing/statement/breakpoint"

Usage:
this.telemetry.recordEvent("devtools.main", "open_file", "debugger", null, {
      mimetype: "application/javascript"
      sourcemapped: true
      wasm: false
      gernerated: false
      time_to_load: "243"
      loaded: false
      framework: "react"
      minified: false
      size: "3120"
      path: "todomvc.com/examples\/react/js/todoModel.js"
});
``` 

https://bugzil.la/1463108
