### ISSUE TITLE
[Scopes] Expand arrows are black in launchpad mode

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#7936]
The expand arrows in Scopes should use a gray fill. They look okay in the Firefox DevTools panel, but are black in launchpad mode.

![screenshot](https://user-images.githubusercontent.com/243601/52572838-0a194880-2e19-11e9-9f12-1998570cec8f.png)

The issue seems to be that we're using a Firefox-only, privileged-content-only method to pass the fill color:

```css
.tree-node button.arrow {
  background: url("/devtools-components/images/arrow.svg") no-repeat;
  background-size: contain;
  background-position: center center;
  width: 10px;
  height: 10px;
  ...
  -moz-context-properties: fill;
  fill: var(--theme-splitter-color, #9B9B9B);
}
```

Also `--theme-splitter-color` is wrong here (not contrasted enough). Instead, we can use the new `--theme-icon-dimmed-color`.
